name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker image
      run: |
        docker build -f docker-image/Dockerfile.devel --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t ghcr.io/jaafar-g/zephyr:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/jaafar-g/zephyr:latest
