name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # This triggers the workflow when a pull request targets the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx for multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1  # Logs in to GitHub Container Registry (GHCR)
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -f Dockerfile --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}:latest

